In [70]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("C:\\Users\\asus\\OneDrive\\Desktop\\project\\warehouse_messy_data.csv")

In [37]:
df.head(5)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,gadget y,ELECTRONICS,Warehouse 2,Aisle 1,300,9.99,Supplier C,In Stock,NaN
1,1435,gadget y,ELECTRONICS,Warehouse 2,Aisle 4,two hundred,19.99,Supplier C,Out of Stock,NaN
2,1860,widget a,CLOTHING,Warehouse 2,Aisle 3,100,19.99,Supplier B,In Stock,20/12/2022
3,1270,gadget z,TOYS,Warehouse 2,Aisle 4,50,49.99,Supplier B,In Stock,20/12/2022
4,1106,widget a,FURNITURE,Warehouse 3,Aisle 3,two hundred,9.99,Supplier D,Out of Stock,25/04/2023

In [45]:
# Strip leading and trailing spaces from string columns 
for column in df.select_dtypes(include = ['object']).columns: df[column]=df[column].str.strip()

In [151]:
df.head(-10)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,Gadget Y,Electronics,Warehouse 2,Aisle 1,300.000000,9.990000,Supplier C,In Stock,NaT
1,1435,Gadget Y,Electronics,Warehouse 2,Aisle 4,200.000000,19.990000,Supplier C,Out of Stock,NaT
2,1860,Widget A,Clothing,Warehouse 2,Aisle 3,100.000000,19.990000,Supplier B,In Stock,2022-12-20
3,1270,Gadget Z,Toys,Warehouse 2,Aisle 4,50.000000,49.990000,Supplier B,In Stock,2022-12-20
4,1106,Widget A,Furniture,Warehouse 3,Aisle 3,200.000000,9.990000,Supplier D,Out of Stock,2023-04-25
...,...,...,...,...,...,...,...,...,...,...
985,1546,Widget C,Furniture,Warehouse 2,Aisle 2,161.401425,9.990000,Supplier C,Out of Stock,2023-01-15
986,1252,Gadget Y,Clothing,Warehouse 3,Aisle 4,200.000000,28.085839,Supplier A,In Stock,2023-03-05
987,1389,Gadget Z,Electronics,Warehouse 1,Aisle 5,300.000000,29.990000,Supplier D,Low Stock,2023-01-15
988,1593,Widget B,Clothing,Warehouse 1,Aisle 1,100.000000,28.085839,Supplier A,Out of Stock,2023-04-25
989,1882,Gadget X,Furniture,Warehouse 2,Aisle 5,200.000000,9.990000,Supplier D,Out of Stock,2023-03-05

In [58]:
# Convert Product Name to proper case 
df['Product Name']= df['Product Name'].str.title()

In [60]:
# convert category
df['Category']= df['Category'].str.capitalize()

In [62]:
df.head(5)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,Gadget Y,Electronics,Warehouse 2,Aisle 1,300,9.99,Supplier C,In Stock,NaN
1,1435,Gadget Y,Electronics,Warehouse 2,Aisle 4,two hundred,19.99,Supplier C,Out of Stock,NaN
2,1860,Widget A,Clothing,Warehouse 2,Aisle 3,100,19.99,Supplier B,In Stock,20/12/2022
3,1270,Gadget Z,Toys,Warehouse 2,Aisle 4,50,49.99,Supplier B,In Stock,20/12/2022
4,1106,Widget A,Furniture,Warehouse 3,Aisle 3,two hundred,9.99,Supplier D,Out of Stock,25/04/2023

In [98]:
# Correct the Quantity column 
df['Quantity']= df['Quantity'].replace('two hundred',200) # replaces 'two hundred' with 200
# replace NAN with np.nan
df['Quantity']= df['Quantity'].replace('NAN', np.nan)
#convert to numeric
df['Quantity']= pd.to_numeric(df['Quantity'], errors ='coerce')

In [104]:
# correcting the price column 
df['Price']= df['Price'].replace('NAN',np.nan)
df['Price']= pd.to_numeric(df['Price'], errors = 'coerce')

In [118]:
# correcting the last restocked column
df['Last Restocked'] = df['Last Restocked'].replace('NAN', np.nan)
df['Last Restocked'] = pd.to_datetime(df['Last Restocked'], errors ='coerce')

In [136]:
df.head(5)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,Gadget Y,Electronics,Warehouse 2,Aisle 1,300.0,9.99,Supplier C,In Stock,NaT
1,1435,Gadget Y,Electronics,Warehouse 2,Aisle 4,200.0,19.99,Supplier C,Out of Stock,NaT
2,1860,Widget A,Clothing,Warehouse 2,Aisle 3,100.0,19.99,Supplier B,In Stock,2022-12-20
3,1270,Gadget Z,Toys,Warehouse 2,Aisle 4,50.0,49.99,Supplier B,In Stock,2022-12-20
4,1106,Widget A,Furniture,Warehouse 3,Aisle 3,200.0,9.99,Supplier D,Out of Stock,2023-04-25

*Handling Missing Values*

In [145]:
# Fill NaN values with a default value or strategy, here we use mean for numeric columns
df['Quantity'].fillna(df['Quantity'].mean(), inplace = True)
df['Price'].fillna(df['Price'].mean(), inplace = True)

C:\Users\asus\AppData\Local\Temp\ipykernel_19808\3492332038.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].mean(), inplace = True)
C:\Users\asus\AppData\Local\Temp\ipykernel_19808\3492332038.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(df['Price'].mean(), inplace = True)

In [157]:
# Fill NaN values for categorical columns with a placeholder or most frequent value 
df['Product Name'].fillna('Unknown Product', inplace=True) 
df['Category'].fillna('Unknown Category', inplace=True) 
df['Warehouse'].fillna(df['Warehouse'].mode()[0], inplace=True) 
df['Location'].fillna('Unknown Location', inplace=True) 
df['Supplier'].fillna(df['Supplier'].mode()[0], inplace=True) 
df['Status'].fillna(df['Status'].mode()[0], inplace=True) 
df['Last Restocked'].fillna(pd.to_datetime('today'), inplace=True)

C:\Users\asus\AppData\Local\Temp\ipykernel_19808\4256620856.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Product Name'].fillna('Unknown Product', inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_19808\4256620856.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Category'].fillna('Unknown Category', inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_19808\4256620856.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Warehouse'].fillna(df['Warehouse'].mode()[0], inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_19808\4256620856.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Location'].fillna('Unknown Location', inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_19808\4256620856.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Supplier'].fillna(df['Supplier'].mode()[0], inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_19808\4256620856.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Status'].fillna(df['Status'].mode()[0], inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_19808\4256620856.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Last Restocked'].fillna(pd.to_datetime('today'), inplace=True)

In [161]:
df.head(5)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,Gadget Y,Electronics,Warehouse 2,Aisle 1,300.0,9.99,Supplier C,In Stock,2025-03-24 22:58:57.904382
1,1435,Gadget Y,Electronics,Warehouse 2,Aisle 4,200.0,19.99,Supplier C,Out of Stock,2025-03-24 22:58:57.904382
2,1860,Widget A,Clothing,Warehouse 2,Aisle 3,100.0,19.99,Supplier B,In Stock,2022-12-20 00:00:00.000000
3,1270,Gadget Z,Toys,Warehouse 2,Aisle 4,50.0,49.99,Supplier B,In Stock,2022-12-20 00:00:00.000000
4,1106,Widget A,Furniture,Warehouse 3,Aisle 3,200.0,9.99,Supplier D,Out of Stock,2023-04-25 00:00:00.000000

In [172]:
# Save the cleaned data to a new CSV file 
df.to_csv('cleaned_warehouse_messy_data.csv', index=False)